INSERT INTO HEALTH_PROFILE (ID, USERNAME) VALUES (1, 'admin');
INSERT INTO HEALTH_PROFILE (ID, USERNAME) VALUES (2, 'john');
INSERT INTO HEALTH_PROFILE (ID, USERNAME) VALUES (96, 'deleteme');
INSERT INTO HEALTH_PROFILE (ID, USERNAME) VALUES (97, 'deleteme2');
INSERT INTO HEALTH_PROFILE (ID, USERNAME) VALUES (98, 'jane');
INSERT INTO HEALTH_PROFILE (ID, USERNAME) VALUES (99, 'dave');

/* HEART_RATE, ECG,BP_DIASTOLIC, BP_SYSTOLIC, BLOOD_OXYGEN_LEVEL */
INSERT INTO HEALTH_METRIC ( VALUE, TYPE, PROFILE_ID) VALUES (60, 'HEART_RATE', 1);
INSERT INTO HEALTH_METRIC ( VALUE, TYPE, PROFILE_ID) VALUES (60, 'HEART_RATE', 2);
INSERT INTO HEALTH_METRIC ( VALUE, TYPE, PROFILE_ID) VALUES (80, 'ECG', 2);
INSERT INTO HEALTH_METRIC ( VALUE, TYPE, PROFILE_ID) VALUES (120, 'BP_SYSTOLIC', 2);
INSERT INTO HEALTH_METRIC ( VALUE, TYPE, PROFILE_ID) VALUES (80, 'BP_DIASTOLIC', 2);
INSERT INTO HEALTH_METRIC ( VALUE, TYPE, PROFILE_ID) VALUES (92, 'BLOOD_OXYGEN_LEVEL', 2);

INSERT INTO HEALTH_METRIC ( VALUE, TYPE, PROFILE_ID) VALUES (93, 'BLOOD_OXYGEN_LEVEL', 96);
INSERT INTO HEALTH_METRIC ( VALUE, TYPE, PROFILE_ID) VALUES (93, 'BP_DIASTOLIC', 96);
INSERT INTO HEALTH_METRIC ( VALUE, TYPE, PROFILE_ID) VALUES (93, 'BLOOD_OXYGEN_LEVEL', 97);
INSERT INTO HEALTH_METRIC ( VALUE, TYPE, PROFILE_ID) VALUES (93, 'BLOOD_OXYGEN_LEVEL', 98);
INSERT INTO HEALTH_METRIC ( VALUE, TYPE, PROFILE_ID) VALUES (90, 'BLOOD_OXYGEN_LEVEL', 99);