INSERT INTO HEALTH_PROFILE (ID, USERNAME) VALUES (1, 'admin');
INSERT INTO HEALTH_PROFILE (ID, USERNAME) VALUES (2, 'john');
INSERT INTO HEALTH_PROFILE (ID, USERNAME) VALUES (98, 'jane');
INSERT INTO HEALTH_PROFILE (ID, USERNAME) VALUES (99, 'dave');
/* HEART_RATE, ECG,BP_DIASTOLIC, BP_SYSTOLIC, BLOOD_OXYGEN_LEVEL */
INSERT INTO HEALTH_METRIC (ID, VALUE, TYPE, PROFILE_ID) VALUES (1, 60, 'HEART_RATE', 2);
INSERT INTO HEALTH_METRIC (ID, VALUE, TYPE, PROFILE_ID) VALUES (2, 80, 'ECG', 2);
INSERT INTO HEALTH_METRIC (ID, VALUE, TYPE, PROFILE_ID) VALUES (3, 120, 'BP_SYSTOLIC', 2);
INSERT INTO HEALTH_METRIC (ID, VALUE, TYPE, PROFILE_ID) VALUES (4, 80, 'BP_DIASTOLIC', 2);
INSERT INTO HEALTH_METRIC (ID, VALUE, TYPE, PROFILE_ID) VALUES (5, 92, 'BLOOD_OXYGEN_LEVEL', 2);
INSERT INTO HEALTH_METRIC (ID, VALUE, TYPE, PROFILE_ID) VALUES (6, 93, 'BLOOD_OXYGEN_LEVEL', 98);
INSERT INTO HEALTH_METRIC (ID, VALUE, TYPE, PROFILE_ID) VALUES (7, 90, 'BLOOD_OXYGEN_LEVEL', 99);